version: "3.8"

services:
  mysqldb:
    container_name: mysqldb-container
    image: mysql
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rab3tech_db

  book-app-rest-api:
    container_name: book-app-rest-api-container
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "9999:8080"
    depends_on:
      - mysqldb
    restart: on-failure
